version: "3.9"
services:
  redis:
    image: redis/redis-stack
    volumes:
      - redis_data:/data:rw
    ports:
      - 6379:8080
    restart: unless-stopped
  
  api: 
    image: tide
    ports: 
      - 8080-6379
